In [1]:
from sqlalchemy import create_engine
import pandas as pd
import numpy as np

# Receita

### CNPJ

In [13]:
disk_engine = create_engine(r'sqlite:///C:\Users\Renato\OneDrive\Pessoal\RSL Consultoria\Horizon\05-Tese Psiquiatria\HZN-tese-psiquiatria\psiquiatria.db')
df_RF = pd.read_sql_query("SELECT CO_UNIDADE,CO_CNES,cnpj,NO_RAZAO_SOCIAL,cep  FROM receita",disk_engine) #42 EMPRESAS PRA FAZER SCRAPING
df_RF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21071 entries, 0 to 21070
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   CO_UNIDADE       21071 non-null  object 
 1   CO_CNES          21071 non-null  int64  
 2   cnpj             21071 non-null  float64
 3   NO_RAZAO_SOCIAL  21071 non-null  object 
 4   cep              19113 non-null  object 
dtypes: float64(1), int64(1), object(3)
memory usage: 823.2+ KB


In [14]:
df_RF.head()

CO_UNIDADE  CO_CNES          cnpj                   NO_RAZAO_SOCIAL  \
0  3,53431E+12  7970994  1.358472e+13         TASINAFFO ANTONIASSI LTDA   
1  2,92741E+12  7978359  2.308397e+13             JM PSICOLOGIA LTDA ME   
2  5,10791E+12  7824580  2.301707e+13  M G DE CARVALHO SANTOS EIRELI ME   
3  3,55031E+12  7912900  2.365926e+13      ONO REVELES MEDICINA E SAUDE   
4  3,15401E+12  7909454  2.397397e+13             BRAZ BIFANO BASTOS ME   

          cep  
0  14.620-000  
1        None  
2        None  
3  05.409-001  
4        None

In [4]:
df_RF['cnes_string'] = df_RF['CO_CNES'].astype(str)
rst = df_RF['cnes_string'].map(lambda calc: len(calc))
print("No. of characters in each word in the given series:")
rst.unique() #CNES FORMATO OK

No. of characters in each word in the given series:


array([7], dtype=int64)

In [5]:
#CNPJ
df_RF['cnpj_int'] = df_RF['cnpj'].apply(np.int64)
df_RF['CNPJ_string'] = df_RF['cnpj_int'].astype(str)
df_RF['CNPJ_Lenght'] = df_RF['CNPJ_string'].map(lambda calc: len(calc))
print("No. of characters in each word in the given series:")
df_RF['CNPJ_Lenght'].unique() #CNPJ FORMATO OK

No. of characters in each word in the given series:


array([14, 13, 12, 11, 10], dtype=int64)

In [6]:
df_RF.loc[df_RF['CNPJ_Lenght']==10,'CNPJ_string']='0000'+df_RF['CNPJ_string']
df_RF.loc[df_RF['CNPJ_Lenght']==11,'CNPJ_string']='000'+df_RF['CNPJ_string']
df_RF.loc[df_RF['CNPJ_Lenght']==12,'CNPJ_string']='00'+df_RF['CNPJ_string']
df_RF.loc[df_RF['CNPJ_Lenght']==13,'CNPJ_string']='0'+df_RF['CNPJ_string']

In [7]:
df_RF['CNPJ_NEW_Lenght'] = df_RF['CNPJ_string'].map(lambda calc: len(calc))
df_RF['CNPJ_NEW_Lenght'].unique()# adicionado todos zeros antes de cada cnpj para todos ficarem com 14 digitos


array([14], dtype=int64)

In [8]:
df_RF.columns

Index(['CO_UNIDADE', 'CO_CNES', 'cnpj', 'NO_RAZAO_SOCIAL', 'cep', 'cep',
       'cnes_string', 'cnpj_int', 'CNPJ_string', 'CNPJ_Lenght',
       'CNPJ_NEW_Lenght'],
      dtype='object')

In [9]:
df_RF['cnpj']=df_RF['CNPJ_string'] #jogando fora cnpj antigo e usando o que geramos acima
# criando dict
dict_RF_CNPJ = df_RF.set_index('CO_CNES')['cnpj'].to_dict() # PASSAR ESSE DICT NA BASE.CSV
# dict_CNES_CNPJ 

### CEP

In [18]:
#CEP
df_RF['cep_Lenght'] = df_RF['cep'].fillna('0').map(lambda calc: len(calc))
print("No. of characters in each word in the given series:")
df_RF['cep_Lenght'].unique() #cep FORMATO OK

No. of characters in each word in the given series:


array([10,  1], dtype=int64)

In [45]:
df_RF[df_RF['cep_Lenght']==10].head(3)

CO_UNIDADE  CO_CNES          cnpj  \
0  3,53431E+12  7970994  1.358472e+13   
3  3,55031E+12  7912900  2.365926e+13   
5  4,20541E+12  7949278  1.014587e+13   

                              NO_RAZAO_SOCIAL         cep  cep_Lenght  
0                   TASINAFFO ANTONIASSI LTDA  14.620-000          10  
3                ONO REVELES MEDICINA E SAUDE  05.409-001          10  
5  BECKER E BENDER CLINICA PSIQUIATRICA SS ME  88.015-200          10

In [49]:
#tirando . e - do cep RF
df_RF['cep'] = df_RF['cep'].str.replace('.','').str.replace('-','')

<ipython-input-49-7ca8f39337c9>:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df_RF['cep'] = df_RF['cep'].str.replace('.','').str.replace('-','')


In [50]:
df_RF['cep_Lenght'] = df_RF['cep'].fillna('0').map(lambda calc: len(calc))
print("No. of characters in each word in the given series:")
df_RF['cep_Lenght'].unique() #cep FORMATO OK

No. of characters in each word in the given series:


array([8, 1], dtype=int64)

In [53]:
dict_RF_CEP = df_RF.set_index('CO_CNES')['cep'].to_dict() # PASSAR ESSE DICT NA BASE.CSV
# dict_RF_CEP


# CNES


### CNPJ

In [22]:
disk_engine = create_engine(r'sqlite:///C:\Users\Renato\OneDrive\Pessoal\RSL Consultoria\Horizon\05-Tese Psiquiatria\HZN-tese-psiquiatria\psiquiatria.db')
df_CNES = pd.read_sql_query("SELECT id,cnes,\"Nome Fantasia\", \"Razão Social\",CNPJ,CEP  FROM DATA",disk_engine) #42 EMPRESAS PRA FAZER SCRAPING
df_CNES.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 393062 entries, 0 to 393061
Data columns (total 6 columns):
 #   Column         Non-Null Count   Dtype  
---  ------         --------------   -----  
 0   id             393062 non-null  int64  
 1   cnes           393062 non-null  int64  
 2   Nome Fantasia  393043 non-null  object 
 3   Razão Social   393059 non-null  object 
 4   CNPJ           164043 non-null  float64
 5   CEP            393062 non-null  int64  
dtypes: float64(1), int64(3), object(2)
memory usage: 18.0+ MB


In [23]:
df_CNES['cnes'].nunique()

393062

In [24]:
df_CNES['cnes_string'] = df_CNES['cnes'].astype(str)
rst = df_CNES['cnes_string'].map(lambda calc: len(calc))
print("No. of characters in each word in the given series:")
rst.unique() #CNES FORMATO OK

No. of characters in each word in the given series:


array([7], dtype=int64)

In [25]:
df_CNES = df_CNES[df_CNES['CNPJ'].notnull()]

In [26]:
#CNPJ
df_CNES['CNPJ_int'] = df_CNES['CNPJ'].apply(np.int64)
df_CNES['CNPJ_string'] = df_CNES['CNPJ_int'].astype(str)
df_CNES['CNPJ_Lenght'] = df_CNES['CNPJ_string'].map(lambda calc: len(calc))
print("No. of characters in each word in the given series:")
df_CNES['CNPJ_Lenght'].unique() #CNPJ FORMATO OK

No. of characters in each word in the given series:


array([13, 14, 12, 11,  9, 10,  8,  6], dtype=int64)

In [27]:
df_CNES.loc[df_CNES['CNPJ_Lenght']==6,'CNPJ_string']='00000000'+df_CNES['CNPJ_string']
df_CNES.loc[df_CNES['CNPJ_Lenght']==8,'CNPJ_string']='000000'+df_CNES['CNPJ_string']
df_CNES.loc[df_CNES['CNPJ_Lenght']==9,'CNPJ_string']='00000'+df_CNES['CNPJ_string']
df_CNES.loc[df_CNES['CNPJ_Lenght']==10,'CNPJ_string']='0000'+df_CNES['CNPJ_string']
df_CNES.loc[df_CNES['CNPJ_Lenght']==11,'CNPJ_string']='000'+df_CNES['CNPJ_string']
df_CNES.loc[df_CNES['CNPJ_Lenght']==12,'CNPJ_string']='00'+df_CNES['CNPJ_string']
df_CNES.loc[df_CNES['CNPJ_Lenght']==13,'CNPJ_string']='0'+df_CNES['CNPJ_string']


In [28]:
df_CNES['CNPJ_NEW_Lenght'] = df_CNES['CNPJ_string'].map(lambda calc: len(calc))
df_CNES['CNPJ_NEW_Lenght'].unique()# adicionado todos zeros antes de cada cnpj para todos ficarem com 14 digitos

array([14], dtype=int64)

In [29]:
dict_CNES_CNPJ = df_CNES.set_index('cnes')['CNPJ_string'].to_dict() # PASSAR ESSE DICT NA BASE.CSV
# dict_CNES_CNPJ


### CEP

In [32]:
#CEP
# df_CNES['CEP_int'] = df_CNES['CEP'].apply(np.int64)
df_CNES['CEP_string'] = df_CNES['CEP'].astype(str)
df_CNES['CEP_Lenght'] = df_CNES['CEP_string'].map(lambda calc: len(calc))
print("No. of characters in each word in the given series:")
df_CNES['CEP_Lenght'].unique() #CEP FORMATO OK

No. of characters in each word in the given series:


array([8, 7], dtype=int64)

In [37]:
df_CNES[df_CNES['CEP_Lenght']==7].head(2)

id     cnes                Nome Fantasia  \
25  3550307732104  7732104        M FERRARI ODONTOLOGIA   
31  3550309577130  9577130  INCREASING SERVICOS MEDICOS   

                        Razão Social          CNPJ      CEP cnes_string  \
25        M FERRARI ODONTOLOGIA LTDA  2.139645e+13  5042001     7732104   
31  INCREASING SERVICOS MEDICOS LTDA  2.513797e+13  4026000     9577130   

          CNPJ_int     CNPJ_string  CNPJ_Lenght  CNPJ_NEW_Lenght CEP_string  \
25  21396448000146  21396448000146           14               14    5042001   
31  25137965000151  25137965000151           14               14    4026000   

    CEP_Lenght  
25           7  
31           7

In [40]:
df_CNES.loc[df_CNES['CEP_Lenght']==7,'CEP_string']='0'+df_CNES['CEP_string']

In [42]:
df_CNES['CEP_NEW_Lenght'] = df_CNES['CEP_string'].map(lambda calc: len(calc))
df_CNES['CEP_NEW_Lenght'].unique()# adicionado todos zeros antes de cada CEP para todos ficarem com 8 digitos


array([8], dtype=int64)

In [44]:
dict_CNES_CEP = df_CNES.set_index('cnes')['CEP_string'].to_dict() # PASSAR ESSE DICT NA BASE.CSV
# dict_CNES_CEP

# Importando BASE.csv

In [54]:
df = pd.read_csv(r'App\base.csv', sep = ';', encoding = 'latin1')

<ipython-input-54-dd13301c0222>:1: DtypeWarning: Columns (92,93,123,153,155,156,180) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r'App\base.csv', sep = ';', encoding = 'latin1')


#### Passando dicts de CNPJ

In [55]:
df[['cnes','CNPJ','cnpj']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21053 entries, 0 to 21052
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   cnes    21053 non-null  int64 
 1   CNPJ    21053 non-null  object
 2   cnpj    21053 non-null  object
dtypes: int64(1), object(2)
memory usage: 493.6+ KB


In [56]:
df[['cnes','CNPJ','cnpj']].head(3)

cnes         CNPJ         cnpj
0  7035594  1,40884E+13  1,40884E+13
1  9575782  2,44686E+13  2,44686E+13
2  9577130   2,5138E+13   2,5138E+13

In [57]:
df['cnpj'] = df['cnes'].map(dict_RF_CNPJ) #reescrevendo a col cnpj da receita a partir do dict
df['CNPJ'] = df['cnes'].map(dict_CNES_CNPJ) #reescrevendo a col cnpj da base do CNES a partir do dict

In [58]:
df[['cnes','CNPJ','cnpj']].head(3)

cnes            CNPJ            cnpj
0  7035594  14088437000133  14088437000133
1  9575782  24468575000100  24468575000100
2  9577130  25137965000151  25137965000151

In [59]:
df[['cnes','CNPJ','cnpj']].info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21053 entries, 0 to 21052
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   cnes    21053 non-null  int64 
 1   CNPJ    21053 non-null  object
 2   cnpj    21053 non-null  object
dtypes: int64(1), object(2)
memory usage: 493.6+ KB


#### Passando dicts de cep

In [60]:
df[['cnes','CEP','cep']].info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21053 entries, 0 to 21052
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   cnes    21053 non-null  int64 
 1   CEP     21053 non-null  int64 
 2   cep     19095 non-null  object
dtypes: int64(2), object(1)
memory usage: 493.6+ KB


In [61]:
df[['cnes','CEP','cep']].head(3)


cnes       CEP         cep
0  7035594  72215170  72.215-170
1  9575782  78563000  78.563-000
2  9577130   4026000  04.026-000

In [62]:
#passar os dicts acima
df['cep'] = df['cnes'].map(dict_RF_CEP) #reescrevendo a col cep da receita a partir do dict
df['CEP'] = df['cnes'].map(dict_CNES_CEP) #reescrevendo a col cep da base do CEP a partir do dict

In [63]:
df[['cnes','CEP','cep']].head(3)


cnes       CEP       cep
0  7035594  72215170  72215170
1  9575782  78563000  78563000
2  9577130  04026000  04026000

# Extraindo a base

In [64]:
df.to_csv(r'App\base2.csv',index=False)

Testando impor da base no streamlit

In [ ]:
df_stream = pd.read_csv(r'App\base2.csv',dtype={'cnpj': object,'CNPJ': object,'cep': object,'CEP': object})

In [ ]:
df_stream[['cnpj','CNPJ']]#.info()